# Generated by Django 5.0.2 on 2024-03-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_video_time_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
