# Generated by Django 5.0.2 on 2024-03-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_course_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Certificate',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
