# Generated by Django 5.0.2 on 2024-03-10 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_quiztopic_subsubtopic_mcq_subtopic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Resources_course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='quiz_topic',
        ),
        migrations.RemoveField(
            model_name='subsubtopic',
            name='subtopic',
        ),
        migrations.CreateModel(
            name='Resources_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('answer', models.IntegerField()),
                ('option_one', models.CharField(max_length=100)),
                ('option_two', models.CharField(max_length=100)),
                ('option_three', models.CharField(blank=True, max_length=100)),
                ('option_four', models.CharField(blank=True, max_length=100)),
                ('marks', models.IntegerField(default=1)),
                ('Resources_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Resources_ScoreBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('Resources_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MCQ',
        ),
        migrations.DeleteModel(
            name='QuizTopic',
        ),
        migrations.DeleteModel(
            name='SubSubTopic',
        ),
        migrations.DeleteModel(
            name='SubTopic',
        ),
    ]
