# Generated by Django 5.0.2 on 2024-03-10 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_resources_question_resources_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources_scoreboard',
            name='Resources_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.resources_course'),
        ),
    ]
